name: Java CI and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    
    # Set up Java (you might want to change the JDK version to 1.5.0 or compatible)
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    # Install Ant
    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    # Build the JE project using Ant
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    # Create a release in GitHub
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}  # Use branch/tag name or set it explicitly
        release_name: JE Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    # Upload the generated .jar file to the release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/lib/je.jar  # Adjust this path based on your Ant build output
        asset_name: je.jar  # Name of the uploaded asset
        asset_content_type: application/java-archive
