name: Java CI and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install -y ant

    - name: Build with Ant
      run: ant -noinput -buildfile build.xml

    - name: List files in build directory
      run: ls -R build/lib

    - name: Rename .jar file if necessary
      run: |
        mv build/lib/actual-name.jar build/lib/je-M.N.P.jar || echo "No need to rename"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: JE Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/lib/je-M.N.P.jar
        asset_name: je-M.N.P.jar
        asset_content_type: application/java-archive
